// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOFEHdQgWl25dY6u5azPnf7rIETYKi_n4',
    appId: '1:107094866246:web:d41e4dc5889fcf4be54d47',
    messagingSenderId: '107094866246',
    projectId: 'projectfirebase-5f8d6',
    authDomain: 'projectfirebase-5f8d6.firebaseapp.com',
    storageBucket: 'projectfirebase-5f8d6.firebasestorage.app',
    measurementId: 'G-95P4ZWXBVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAisZKPJVF0OKwpGpnwML6Eo43gTqQp0X4',
    appId: '1:107094866246:android:9e2f3359922df8cfe54d47',
    messagingSenderId: '107094866246',
    projectId: 'projectfirebase-5f8d6',
    storageBucket: 'projectfirebase-5f8d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuVXcxSQ6X8u8e6hz2hsLWNCcG2SjkCbM',
    appId: '1:107094866246:ios:03bd82593b984f82e54d47',
    messagingSenderId: '107094866246',
    projectId: 'projectfirebase-5f8d6',
    storageBucket: 'projectfirebase-5f8d6.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuVXcxSQ6X8u8e6hz2hsLWNCcG2SjkCbM',
    appId: '1:107094866246:ios:03bd82593b984f82e54d47',
    messagingSenderId: '107094866246',
    projectId: 'projectfirebase-5f8d6',
    storageBucket: 'projectfirebase-5f8d6.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOFEHdQgWl25dY6u5azPnf7rIETYKi_n4',
    appId: '1:107094866246:web:c6db9bcdfde4742fe54d47',
    messagingSenderId: '107094866246',
    projectId: 'projectfirebase-5f8d6',
    authDomain: 'projectfirebase-5f8d6.firebaseapp.com',
    storageBucket: 'projectfirebase-5f8d6.firebasestorage.app',
    measurementId: 'G-BG80MEJ7Z3',
  );
}
